# Generated by Django 5.2.4 on 2025-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
