# Generated by Django 5.2.4 on 2025-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facilityavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
