# Generated by Django 5.2.4 on 2025-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dog_photo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='daily_logs/'),
        ),
    ]
