# Generated by Django 5.2.4 on 2025-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250801_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_base64',
        ),
        migrations.AddField(
            model_name='dog',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
