# Generated by Django 5.2.4 on 2025-08-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_photo_url_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_url',
        ),
    ]
