# Generated by Django 5.2.4 on 2025-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_photo_url_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='dog_photos/'),
        ),
    ]
