# Generated by Django 5.2.4 on 2025-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_photo_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='supabase_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
