# Generated by Django 5.2.4 on 2025-08-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_dog_photo_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_base64',
        ),
    ]
