# Generated by Django 5.2.4 on 2025-08-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_photo_url_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_url',
        ),
    ]
