# Generated by Django 5.2.4 on 2025-08-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_photo_url_temporarily'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
