# Generated by Django 5.2.4 on 2025-08-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_photo_url_final_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_url',
        ),
    ]
