# Generated by Django 5.2.4 on 2025-08-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_photo_url_working'),
    ]

    operations = [
    ]
